import { PlayerAttacks } from '../systems/attack';
import { Gravity } from '../systems/gravity';
import { RecordHistory } from '../systems/history';
import { LedgeGrabDetection } from '../systems/ledgeGrabDetection';
import { OutOfBoundsCheck } from '../systems/outOfBounds';
import { PlatformDetection } from '../systems/platformCollision';
import { PlayerCollisionDetection } from '../systems/playerCollision';
import { PlayerInput } from '../systems/playerInput';
import { PlayerSensors } from '../systems/sensors';
import { ShieldRegen } from '../systems/shieldRegen';
import { StageCollisionDetection } from '../systems/stageCollision';
import { Flags } from '../systems/flags';
import { ApplyVelocity } from '../systems/velocity';
import { ApplyVelocityDecay } from '../systems/velocityDecay';
import { PlayerGrabs } from '../systems/grab';
import { GrabMeter } from '../systems/grabMeter';
import { WallKick } from '../systems/wallKick';
import { World } from '../world/world';
import { GameLoop } from './jazzLocal';
import { PlayerThrows } from '../systems/throw';

export const DefaultGameLoop: GameLoop = (w: World) => {
  Flags(w);
  PlayerInput(w);
  Gravity(w);
  ApplyVelocity(w);
  ApplyVelocityDecay(w);
  PlayerCollisionDetection(w);
  PlatformDetection(w);
  StageCollisionDetection(w);
  WallKick(w);
  LedgeGrabDetection(w);
  PlayerSensors(w);
  PlayerThrows(w);
  PlayerAttacks(w);
  ShieldRegen(w);
  GrabMeter(w);
  PlayerGrabs(w);
  OutOfBoundsCheck(w);
  RecordHistory(w);
};
