const fs = require('fs');
const path = require('path');

const BITS = 10;
const Q = 1 << BITS;
const LUT_SIZE = 2048;

function floatToFixed(n: number): number {
    return Math.floor(n * Q);
}

function generateLuts() {
    const sinLut = new Int32Array(LUT_SIZE);
    const cosLut = new Int32Array(LUT_SIZE);

    for (let i = 0; i < LUT_SIZE; i++) {
        const angle = (i / LUT_SIZE) * 2 * Math.PI;
        sinLut[i] = floatToFixed(Math.sin(angle));
        cosLut[i] = floatToFixed(Math.cos(angle));
    }

    const lutFilePath = path.join(__dirname, 'LUTS.ts');

    let fileContent = '// This file is generated by generate-luts.ts. Do not edit manually.\n\n';
    fileContent += 'export const SIN_LUT = new Int32Array([\n';
    fileContent += sinLut.join(',\n');
    fileContent += '\n]);\n\n';
    fileContent += 'export const COS_LUT = new Int32Array([\n';
    fileContent += cosLut.join(',\n');
    fileContent += '\n]);\n\n';
    fileContent += `export const LUT_SIZE = ${LUT_SIZE};\n`;

    fs.writeFileSync(lutFilePath, fileContent.trim());
    console.log(`LUTs generated and saved to ${lutFilePath}`);
}

generateLuts();