import fs from 'fs';
import path from 'path';

const LUT_SIZE = 512;
const ATAN2_SIZE = 128;

const BITS = 10;
const Q = 1 << BITS;

function floatToFixed(n: number): number {
  return Math.floor(n * Q);
}

function generateLuts() {
  const sinLut = new Int32Array(LUT_SIZE);
  const cosLut = new Int32Array(LUT_SIZE);
  const atan2Lut = new Int32Array(ATAN2_SIZE * ATAN2_SIZE);

  // Generate sin/cos LUTs
  for (let i = 0; i < LUT_SIZE; i++) {
    const angle = (i / LUT_SIZE) * 2 * Math.PI;
    sinLut[i] = floatToFixed(Math.sin(angle));
    cosLut[i] = floatToFixed(Math.cos(angle));
  }

  // Generate atan2 LUT
  for (let y = 0; y < ATAN2_SIZE; y++) {
    for (let x = 0; x < ATAN2_SIZE; x++) {
      // Map from [0,1023] to [-1,1]
      const xf = (x - ATAN2_SIZE / 2) / (ATAN2_SIZE / 2);
      const yf = (y - ATAN2_SIZE / 2) / (ATAN2_SIZE / 2);

      const angle = Math.atan2(yf, xf);
      // Map [-π,π] directly to [0,LUT_SIZE)
      const angleIndex = Math.floor(
        ((angle + Math.PI) / (2 * Math.PI)) * LUT_SIZE
      );

      atan2Lut[y * ATAN2_SIZE + x] = angleIndex;
    }
  }

  const lutFilePath = path.join(__dirname, 'LUTS.ts');

  let fileContent =
    '// This file is generated by generate-luts.ts. Do not edit manually.\n\n';
  fileContent += 'export const SIN_LUT = new Int32Array([\n';
  fileContent += sinLut.join(',\n');
  fileContent += '\n]);\n\n';
  fileContent += 'export const COS_LUT = new Int32Array([\n';
  fileContent += cosLut.join(',\n');
  fileContent += '\n]);\n\n';
  fileContent += 'export const ATAN2_LUT = new Int32Array([\n';
  fileContent += atan2Lut.join(',\n');
  fileContent += '\n]);\n\n';
  fileContent += `export const LUT_SIZE = ${LUT_SIZE};\n`;
  fileContent += `export const ATAN2_SIZE = ${ATAN2_SIZE};\n`;

  fs.writeFileSync(lutFilePath, fileContent.trim());
  console.log(`LUTs generated and saved to ${lutFilePath}`);
}

generateLuts();
//npx ts-node game/engine/systems/generate-luts.ts
